config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :groups do
    resources :subgroups, only: [:new, :create]
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :personal_access_tokens, only: [:index, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #

  # API
  mount API::Base, at: "/"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @groups = current_user.groups.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is the about page of the GitLab Junior App
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  This is the contact page.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  This is the help page of the GitLab Junior
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <h1>User Groups</h1>
  <p><%=link_to 'New Top Level Group', new_group_path, class: "btn btn-primary", data: { qa_selector: 'new_top_level_group_link' } %></p>
  <% if @groups.any? %>
    <%= render 'shared/groups', groups: @groups %>
  <% end %>
<% else %>
  <div class="center jumbotron">

    <h1>Welcome to GitLab Junior</h1>

    <h2>
      This is the home page for the shiny new GitLab Junior
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary", data: { qa_selector: 'sign_up_link' } %>

  </div>
<% end %>

<%= link_to image_tag("gitlab-logo-500.svg", alt: "GitLab logo", width: "100"),
  "https://www.gitlab.com/" %>