config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :groups do
    resources :subgroups, only: [:new, :create]
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :personal_access_tokens, only: [:index, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #

  # API
  mount API::Base, at: "/"
end

app/models/group.rb
class Group < ApplicationRecord
  delegate :url_helpers, to: 'Rails.application.routes'

  belongs_to :parent_group, class_name: 'Group', optional: true
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :sub_groups, class_name: 'Group', foreign_key: 'parent_group_id', dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates_with GroupOwnerValidator

  def full_path
    path = ["<strong>#{self.name}</strong>"]
    ancestors.each do |ancestor|
      path << ancestor.name
    end
    path.reverse.join(' / ').html_safe
  end

  def breadcrumb
    crumb = []
    crumb << ["<li class='active'>#{self.name}</li>"]
    ancestors.each do |ancestor|
      crumb << "<li>#{group_link(ancestor.name, url_helpers.group_path(ancestor.id))}</li>"
    end
    crumb.reverse.join('').html_safe
  end

  def ancestors
    ancestors = []
    record = self.parent_group
    while record do
      ancestors << record
      record = record.parent_group
    end
    ancestors
  end

  def group_link(name, id, klass = '')
    ActionController::Base.helpers.link_to name, id, class: klass
  end
end

app/controllers/api/v1/groups.rb
module API
  module V1
    class Groups < Grape::API
      include API::V1::Defaults

      resource :groups do
        desc 'Return all groups' do
          success Entities::Group
        end
        params do
          optional :owner_id, type: Integer, desc: 'ID of the owner'
        end
        get do
          groups = params[:owner_id].present? ? Group.where(owner_id: params[:owner_id]) : Group.all
          present groups, with: Entities::Group
        end

        desc 'Return a group'
        params do
          requires :id, type: Integer, desc: 'ID of the group'
        end
        get ':id' do
          group = Group.where(id: params[:id]).first!
          present group, with: API::Entities::Group
        end

        desc 'Delete a group'
        params do
          requires :id, type: Integer, desc: 'ID of the group'
        end
        delete ':id' do
          authenticate!

          group = Group.find(params[:id])

          unauthorized! unless current_user.admin? || current_user == group.owner

          Group.find(params[:id]).destroy
          status 204
        end

        desc 'Return a group\'s subgroups'
        params do
          requires :id, type: Integer, desc: 'ID of the group'
        end
        get ':id/subgroups' do
          group = Group.where(id: params[:id]).first!.sub_groups
          present group, with: API::Entities::Group
        end

        desc 'Create a group'
        params do
          requires :name, type: String, desc: 'The name of the new group'
          requires :description, type: String, desc: 'The description of the new group'
          optional :parent_group_id, type: Integer, desc: 'Id of the parent group'
        end
        post do
          authenticate!

          params = permitted_params
          group = Group.new(params.merge({owner_id: current_user.id}))
          if group.save
            present group, with: API::Entities::Group
          else
            render_validation_error!(group)
          end
        end
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
  before_action :allowed_user, only: [:create, :edit, :update, :destroy]

  def new
    @new_group = current_user.groups.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:success] = 'Group updated'
      redirect_to @group
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    @new_group = current_user.groups.build(group_params)
    if @new_group.save
      flash[:success] = "Group created!"
      redirect_to @new_group
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @group = Group.find(params[:id])
    @sub_groups = @group.sub_groups.paginate(page: params[:page])
  end

  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Group deleted"
    if request.referrer.nil?
      redirect_to root_url, status: :see_other
    else
      redirect_to request.referrer, status: :see_other
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :owner_id, :parent_group_id)
  end

  def allowed_user
    return unless params[:id]
    return if params[:id] && (current_user?(Group.find(params[:id]).owner) || current_user.admin?)

    flash[:danger] = "You are not allowed to perform this action"
    redirect_to(root_url, status: :unauthorized)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', data: { qa_selector: 'name_field' } %>

  <%= f.label :description %>
  <%= f.text_area :description, placeholder: "What is this group about?", data: { qa_selector: 'description_field' } %>

  <%= f.submit button_name, class: "btn btn-primary", data: { qa_selector: 'submit_form_button' } %>
<% end %>

app/views/groups/_group.html.erb
<li class="list-group-item" id="group-<%= group.id %>">
  <h4 class="name">
    <%= link_to group.full_path, group %>
    <%= link_to user_path(group.owner) do %>
      <i class="glyphicon glyphicon-user pull-right"> <%=group.owner.name%></i>
    <% end %>
  </h4>

  <p class="description"><%= group.description %></p>
  <span>
    Created <%= time_ago_in_words(group.created_at) %> ago.
    <% if current_user?(group.owner) || current_user.admin? %>
      <%= link_to group, data: { "turbo-method": :delete, turbo_confirm: "You sure?" } do %>
        <i class="glyphicon glyphicon-trash pull-right"></i>
      <% end %>
      <%= link_to edit_group_path(group) do %>
        <i class="glyphicon glyphicon-edit pull-right">&nbsp;</i>
      <% end %>
    <% end %>
  </span>
</li>

app/views/groups/edit.html.erb
<% provide(:title, 'Create a Group') %>
<h1>Edit Group</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', button_name: 'Update', group: @group %>
  </div>
</div>

app/views/groups/new.html.erb
<% provide(:title, 'Create a Group') %>
<h1>Create a Group</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', button_name: 'Create', group: @new_group %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, 'Group') %>

<ol class="breadcrumb">
  <%= @group.breadcrumb %>
</ol>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @group.name %></h3>
  </div>
  <div class="panel-body">
    <%= @group.description %>
  </div>
</div>

<% if current_user?(@group.owner) %>
  <p><%=link_to 'New Subgroup', new_group_subgroup_path(@group), class: "btn btn-primary" %></p>
<% end %>

<% if @sub_groups.any? %>
  <h1><small>Sub Groups</small></h1>
  <%= render 'shared/groups', groups: @sub_groups.all %>
<% else %>
  <div><h2>This group does not have any subgroups</h2></div>
<% end %>