config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :groups do
    resources :subgroups, only: [:new, :create]
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :personal_access_tokens, only: [:index, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #

  # API
  mount API::Base, at: "/"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://www.gitlab.com">GitLab Junior</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://about.gitlab.com/blog/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "GitLab Junior", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button id="hamburger" type="button" class="navbar-toggle collapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul id="navbar-menu"
          class="nav navbar-nav navbar-right collapse navbar-collapse">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path, data: { qa_selector: 'users_link' } %></li>
          <li class="dropdown" data-qa-selector="account_menu_dropdown">
            <a href="#" id="account" class="dropdown-toggle" data-qa-selector="account_dropdown_link">
              Account <b class="caret"></b>
            </a>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to current_user.name, current_user, data: { qa_selector: 'user_profile_link' }  %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Tokens", personal_access_tokens_path, data: { qa_selector: 'tokens_link' } %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path,
                  data: { "turbo-method": :delete, qa_selector: 'log_out_link' } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, data: { qa_selector: 'log_in_link' } %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>